/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void rollShouldReturnArray() {
        Library lib = new Library();
        int numOfRolls = 5;
        int[] allRolls = lib.roll(numOfRolls);

        assertTrue(allRolls.length == 5);
    }

    @Test
    public void containsDuplicatesShouldReturnBoolean() {
        Library lib = new Library();
        int numOfRolls = 5;
        int[] allRolls = lib.roll(numOfRolls);
        boolean hasDups = lib.containsDups(allRolls);

        assertTrue(hasDups == true || hasDups == false);
    }
}
