/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {
/*********
 * roll tests
 * */
    @Test
    public void rollShouldReturnArray() {
        Library lib = new Library();
        int numOfRolls = 5;
        int[] allRolls = lib.roll(numOfRolls);

        assertTrue(allRolls.length == 5);
    }

/*********
 * containsDuplicates tests
 * */
    @Test
    public void containsDuplicatesShouldReturnTrue() {
        Library lib = new Library();
        int[] arr = { 1, 2, 2, 4, 5 };

        assertTrue(lib.containsDuplicates(arr));
    }

/*********
 * calcAvg tests
 * */
    @Test
    public void calcAvgShouldReturnAvg() {
        Library lib = new Library();
        int[] arr = { 1, 2, 2, 4, 5 };
        double expectedAvg = 2.8;

        assertTrue(lib.calcAvg(arr) == expectedAvg);
    }

/*********
 * calcAllAvgs tests
 * */
    @Test
    public void calcAllAvgsShouldReturnArray() {
        Library lib = new Library();
        int[][] arr = { { 1, 2, 2, 4, 5 }, { 5, 3, 8, 2 } };


        assertTrue(lib.calcAllAvgs(arr).length == 2);
    }

/*********
 * analyzeWeatherData tests
 * */
    @Test
    public void analyzeWeatherDataShouldReturnMissingTemps() {
        Library lib = new Library();

        int[][] arr = {
            {66, 64, 58, 65, 71, 57, 60},
            {57, 65, 65, 70, 72, 65, 51},
            {55, 54, 60, 53, 59, 57, 61},
            {65, 56, 55, 52, 55, 62, 57}
        };

        String missingTemps = "Never saw temperatures: 63, 67, 68, 69";

        assertEquals(lib.analyzeWeatherData(arr), missingTemps);
    }

/*********
 * tally tests
 * */
    @Test
    public void tallyShouldReturnMostVotes() {
        Library lib = new Library();
        List<String> votes = new ArrayList<>();

        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String winner = lib.tally(votes);

        assertEquals("Message", winner);
    }
}


