/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

/**********
 * ROLLING DICE
 * Write a method called roll that accepts an integer n and rolls a six-sided dice n times. The method should return an
 * array containing the values of the rolls.
 * */
    public int[] roll(int n) {

    }
}
