/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {

/**********
 * ROLLING DICE
 *
 * Write a method called roll that accepts an integer n and rolls a six-sided dice n times. The method should return an
 * array containing the values of the rolls.
 * */
    public int[] roll(int n) {
        int[] rolls = new int[n];
        int min = 1;
        int max = 6;

        for (int i = 0; i < n; i++) {
            rolls[i] = (int) (Math.random() * ((max - min) + 1)) + min;
        }

        return rolls;
    }


/*******
 * CONTAINS DUPLICATES
 *
 * Write a method called containsDuplicates that returns true or false depending on whether the array contains duplicate values.
 * */
    public boolean containsDuplicates(int[] arr) {
        for (int i = 0; i < arr.length; i++) {
            for (int j = 0; j < arr.length; j++) {
                if (j == i) return true;
            }
        }

        return false;
    }


/*******
 * Calculating Averages
 *
 * Write a method that accepts an array of integers and calculates and returns the average of all the values in the array.
 * */
    public double calcAvg(int[] arr) {
        double sum = 0;
        double length = arr.length;

        for (int i = 0; i < length; i++) {
            sum += arr[i];
        }

        double avg = sum / length;

        return avg;
    }


/*******
 * Arrays of Arrays
 *
 * Given an array of arrays calculate the average value for each array and return the array with the lowest average.
 * */
    public double[] calcAllAvgs(int[][] arr) {
        int length = arr.length;
        double[] allAvgs = new double[length];

        for (int i = 0; i < length; i++) {
            allAvgs[i] = calcAvg(arr[i]);
        }

        return allAvgs;
    }
}
